name: Export Marimo to HTML-WASM and Zip Artifact

on:
  push:
    branches:
      - master
      tags:
       - '*'

  workflow_dispatch:

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Generate requirements.txt with pipreqs
        uses: ryan-rozario/pipreqs-action@master
        with:
          PROJECT_PATH: .
          REQUIREMENT_PATH: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Export notebook to HTML-WASM
        run: |
          marimo export html-wasm komplizierer.py -o komplizierer --mode run

      - name: Zip exported folder
        run: |
          zip -r komplizierer-html-wasm.zip komplizierer
      
      - name: Create GitHub Release and upload artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "komplizierer-html-wasm.zip"
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Komplizierer HTML-WASM Export."

